# base metadata
name: null
version: 
tags: ['jenny']
description: null
schedule: null

# flow-specific fields
flow_name: null
entrypoint: null
path: null
parameters: {}
parameter_openapi_schema: null

# infra-specific fields
work_pool:
  name: 
  work_queue_name: null
  job_variables: {
    
  }