# base metadata
name: null
version: 
tags: ['jenny']
description: null
schedule: null

# flow-specific fields
flow_name: param-example
entrypoint: null
path: null
parameters: {param: '[{"a": 3}]'}
parameter_openapi_schema: null

# infra-specific fields
work_pool:
  name: 
  work_queue_name: null
  job_variables: {
    test: 33,
    # github: {{ prefect.blocks.github.jen_gh }},
    aci_credentials: "{{ prefect.blocks.azure-container-instance-credentials.azure-ui }}"
  }